### ISSUE TITLE
It's a me problem

### ISSUE THREAD

**Issue by perryc1etown** [teamookla/ookla-open-data#15]
Hello!

I'm a Masters student actually hoping to do exactly this for a different state and am struggling with where to start. 

Is there any assistance you can offer? :) 

Thank you for your time.

**Comment by rbrtmrtn** [comment]
Hey @perryc1etown ! I'm not with Ookla but happened to come across your comment and would be happy to help if I can. Can you say a little more about what you're hoping to do?
